name: 
 
on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜运行
 
jobs:
  crawl:
    runs-on: 
    steps:
      - name: 
        uses: 
 
      - name: 
        uses: 
        with:
          python-version: 3.8
 
      - name: 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 
        env:
          USERNAME: {{}}
          PASSWORD: {{}}
        run: |
          python qq_music_crawler.py --username $USERNAME --password $PASSWORD
      - name: 
        uses: 
        with:
          name: 
          path: 
